spring:
  liquibase:
    enabled: true
  datasource:
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  cloud:
    openfeign:
      client:
        config:
          frame-voice-client:
            url: http://localhost:8083
  kafka:
    bootstrap-servers: localhost:9092

parties:
  kafka:
    authentication:
      username: admin
      password: admin
    producer:
      topic: message

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - health

logging:
  level:
    org.zalando.logbook: TRACE
